import { useState } from 'react'
import dayjs from 'dayjs'
import { FileText, FileSpreadsheet, Eye, Download, History, TrendingUp, TrendingDown, Wallet } from 'lucide-react'
import toast from 'react-hot-toast'
import { useData } from '../context/DataContext'
import PageHeader from '../components/ui/PageHeader'
import Button from '../components/ui/Button'
import Modal from '../components/ui/Modal'
import Badge from '../components/ui/Badge'
import { reportApi } from '../api/report'
import { toCSV, downloadBlob, formatMoney, formatDate } from '../utils/format'
import { getItem, setItem } from '../utils/storage'
import { LS_KEYS } from '../constants'

export default function Reports() {
  const { incomes, expenses, goals, summary, incomeCategories, expenseCategories, budgets } = useData()
  const [previewOpen, setPreviewOpen] = useState(false)
  const [history, setHistory] = useState(() => getItem('finpilot_report_history', []))

  const addToHistory = (type) => {
    const entry = {
      id: `${Date.now()}`,
      type,
      createdAt: dayjs().toISOString(),
      income: summary?.total_income || 0,
      expense: summary?.total_expense || 0,
    }
    const next = [entry, ...history].slice(0, 10)
    setHistory(next)
    setItem('finpilot_report_history', next)
  }

  const downloadPdf = () =>
    toast.promise(reportApi.downloadPdf().then(() => addToHistory('PDF')), {
      loading: 'Generating your PDF report…',
      success: 'PDF report downloaded!',
      error: 'Could not generate report',
    })

  const downloadExcel = () => {
    try {
      const icat = {}
      incomeCategories.forEach((c) => {
        icat[c.category_id] = c.category_name
      })
      const ecat = {}
      expenseCategories.forEach((c) => {
        ecat[c.category_id] = c.category_name
      })
      const incomeCsv = toCSV(
        incomes.map((i) => ({
          Type: 'Income',
          Source: i.source,
          Category: icat[i.category_id] || '',
          Amount: i.amount,
          Method: i.payment_method,
          Date: i.income_date,
        }))
      )
      const expenseCsv = toCSV(
        expenses.map((e) => ({
          Type: 'Expense',
          Merchant: e.merchant,
          Category: ecat[e.category_id] || '',
          Amount: e.amount,
          Method: e.payment_method,
          Date: e.expense_date,
        }))
      )
      const combined = [incomeCsv, '', '======== EXPENSES ========', '', expenseCsv].join('\n')
      downloadBlob(new Blob([combined], { type: 'text/csv;charset=utf-8' }), `FinPilot_Report_${dayjs().format('YYYY-MM-DD')}.csv`)
      addToHistory('Excel')
      toast.success('Excel report downloaded!')
    } catch {
      toast.error('Could not generate Excel export')
    }
  }

  const catMap = {}
  expenseCategories.forEach((c) => {
    catMap[c.category_id] = c.category_name
  })
  const catTotals = {}
  expenses.forEach((e) => {
    const name = catMap[e.category_id] || 'Other'
    catTotals[name] = (catTotals[name] || 0) + Number(e.amount)
  })

  const topCategories = Object.entries(catTotals).sort((a, b) => b[1] - a[1]).slice(0, 5)

  return (
    <div>
      <PageHeader title="Reports" subtitle="Generate, preview and download financial reports" />

      <div className="grid gap-4 lg:grid-cols-2">
        <div className="glass-card card-hover group relative overflow-hidden p-6">
          <div className="pointer-events-none absolute -right-8 -top-8 h-32 w-32 rounded-full bg-gradient-to-br from-red-500 to-rose-600 opacity-10 blur-2xl" />
          <div className="flex items-start justify-between">
            <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-red-500 to-rose-600 text-white shadow-lg">
              <FileText size={24} />
            </div>
            <Badge color="red" dot={false}>PDF</Badge>
          </div>
          <h3 className="mt-4 text-lg font-extrabold text-slate-900 dark:text-white">Monthly PDF Report</h3>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
            A beautifully formatted summary of your income, expenses and goals — generated by the server.
          </p>
          <Button variant="danger" icon={Download} className="mt-5" onClick={downloadPdf}>Download PDF</Button>
        </div>

        <div className="glass-card card-hover group relative overflow-hidden p-6">
          <div className="pointer-events-none absolute -right-8 -top-8 h-32 w-32 rounded-full bg-gradient-to-br from-emerald-500 to-green-600 opacity-10 blur-2xl" />
          <div className="flex items-start justify-between">
            <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-500 to-green-600 text-white shadow-lg">
              <FileSpreadsheet size={24} />
            </div>
            <Badge color="green" dot={false}>Excel / CSV</Badge>
          </div>
          <h3 className="mt-4 text-lg font-extrabold text-slate-900 dark:text-white">Excel Export</h3>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
            Export every income and expense record as a spreadsheet for analysis or tax filing.
          </p>
          <Button variant="secondary" icon={Download} className="mt-5" onClick={downloadExcel}>Export to Excel</Button>
        </div>
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-2">
        <div className="glass-card p-6">
          <h3 className="flex items-center gap-2 text-base font-bold text-slate-900 dark:text-white">
            <Eye size={18} className="text-indigo-500" /> Live Preview
          </h3>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Preview what your report looks like before downloading.</p>
          <div className="mt-4 rounded-2xl border border-dashed border-slate-300 p-4 text-center dark:border-slate-700">
            <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-50 text-indigo-500 dark:bg-indigo-500/10">
              <FileText size={28} />
            </div>
            <p className="mt-3 text-sm font-semibold text-slate-600 dark:text-slate-300">FinPilot Monthly Report</p>
            <Button variant="ghost" size="sm" className="mt-3" onClick={() => setPreviewOpen(true)}>Open preview</Button>
          </div>
        </div>

        <div className="glass-card p-6">
          <h3 className="flex items-center gap-2 text-base font-bold text-slate-900 dark:text-white">
            <History size={18} className="text-violet-500" /> Report History
          </h3>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Your recent downloads, right here.</p>
          <div className="mt-4 space-y-2">
            {history.length === 0 ? (
              <p className="rounded-2xl border border-dashed border-slate-300 p-4 text-center text-sm text-slate-400 dark:border-slate-700">
                No reports generated yet.
              </p>
            ) : (
              history.map((h) => (
                <div key={h.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 dark:border-slate-800">
                  <div className={`flex h-9 w-9 items-center justify-center rounded-xl ${h.type === 'PDF' ? 'bg-red-100 text-red-600 dark:bg-red-500/15' : 'bg-green-100 text-green-600 dark:bg-green-500/15'}`}>
                    {h.type === 'PDF' ? <FileText size={16} /> : <FileSpreadsheet size={16} />}
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-bold text-slate-800 dark:text-slate-100">{h.type} Report</p>
                    <p className="text-xs text-slate-400">{formatDate(h.createdAt, 'DD MMM YYYY, hh:mm A')}</p>
                  </div>
                  <Badge color={h.type === 'PDF' ? 'red' : 'green'} dot={false}>{h.type}</Badge>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      <Modal open={previewOpen} onClose={() => setPreviewOpen(false)} title="Report Preview" subtitle="Monthly financial summary" size="lg" icon={FileText}>
        <div className="space-y-5">
          <div className="rounded-2xl bg-gradient-to-br from-indigo-600 to-violet-700 p-6 text-white">
            <p className="text-xs font-bold uppercase tracking-widest text-white/70">FinPilot AI · Monthly Report</p>
            <p className="mt-1 text-2xl font-extrabold">Financial Summary</p>
            <p className="text-sm text-white/70">{dayjs().format('MMMM YYYY')}</p>
          </div>

          <div className="grid grid-cols-3 gap-3">
            {[
              { label: 'Total Income', value: formatMoney(summary?.total_income), icon: TrendingUp, color: 'text-green-600 bg-green-100 dark:bg-green-500/15 dark:text-green-300' },
              { label: 'Total Expense', value: formatMoney(summary?.total_expense), icon: TrendingDown, color: 'text-red-500 bg-red-100 dark:bg-red-500/15 dark:text-red-300' },
              { label: 'Net Balance', value: formatMoney(summary?.current_balance), icon: Wallet, color: 'text-indigo-600 bg-indigo-100 dark:bg-indigo-500/15 dark:text-indigo-300' },
            ].map((s) => (
              <div key={s.label} className="rounded-2xl border border-slate-100 p-4 text-center dark:border-slate-800">
                <div className={`mx-auto mb-2 flex h-9 w-9 items-center justify-center rounded-xl ${s.color}`}>
                  <s.icon size={16} />
                </div>
                <p className="truncate text-sm font-extrabold text-slate-900 dark:text-white">{s.value}</p>
                <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{s.label}</p>
              </div>
            ))}
          </div>

          <div>
            <h4 className="mb-2 text-sm font-bold text-slate-900 dark:text-white">Top Expense Categories</h4>
            {topCategories.length === 0 ? (
              <p className="text-sm text-slate-400">No expense data yet.</p>
            ) : (
              <div className="space-y-2">
                {topCategories.map(([cat, amount], i) => {
                  const max = topCategories[0]?.[1] || 1
                  const pct = (amount / max) * 100
                  return (
                    <div key={cat}>
                      <div className="flex justify-between text-xs">
                        <span className="font-bold text-slate-600 dark:text-slate-300">{cat}</span>
                        <span className="font-semibold text-slate-500">{formatMoney(amount)}</span>
                      </div>
                      <div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800">
                        <div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-violet-500" style={{ width: `${pct}%` }} />
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </div>

          <div>
            <h4 className="mb-2 text-sm font-bold text-slate-900 dark:text-white">Goals</h4>
            {goals.length === 0 ? (
              <p className="text-sm text-slate-400">No goals created.</p>
            ) : (
              goals.map((g) => (
                <div key={g.goal_id} className="flex justify-between rounded-xl border border-slate-100 px-4 py-2.5 text-sm dark:border-slate-800">
                  <span className="font-semibold text-slate-700 dark:text-slate-200">{g.goal_name}</span>
                  <span className="font-bold text-slate-500">
                    {formatMoney(g.saved_amount)} / {formatMoney(g.target_amount)}
                  </span>
                </div>
              ))
            )}
          </div>

          <Button variant="primary" className="w-full" onClick={() => { setPreviewOpen(false); downloadPdf() }}>
            <Download size={16} /> Download this report
          </Button>
        </div>
      </Modal>
    </div>
  )
}
